language: node_js
node_js:
  - 8.5.0
before_install:
  - npm install
script:
  - npm run lint
  - npm test
  - npm run build
master:
  after_success:
    - node scripts/generate.js -a
    - node scripts/generate.js -r
    - npm run build:site
    - .travis/push.sh
